initial lua
Telltale-Modding-Group/Telltale-Editor pull request #11
Opened 2024-12-14 22:11 UTC by LucasSaragosa

add older lua. move scripts to Scripts/ folder (updated them cd ..), removed unneeded lua sources (eg luac/lua)

2024-12-14 23:37 UTC, asilz reviewed
Looking good!

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +#include <Core/Config.hpp>
pragma once

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void _Shutdown();
What is the reason behind having a shutdown function? Why not have the code in the destructor directly?

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void* _State = NULL; // lua_State specific to the verison.
You could declare
`struct lua_State;`
Then use `lua_State *` instead of `void *`
You can then remove the LSTATE macro

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/ScriptManager.hpp
> +#include <Scripting/LuaManager.hpp>
pragma once

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Core/Config.hpp
> +#define TTE_DEL(_Inst) delete _Inst
The delete does not take in the type, perhaps it should? Not sure if there is a way to get the type through the variable. Maybe we could use templates
```
template <class T> inline T *alloc() { return new T(); }
template <class T> inline void dealloc(T *ptr) { delete ptr; }
```
Or pass in the type in  `#define TTE_DEL(_Type, _Inst) delete _Inst`

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Source/Scripting/LuaManager.cpp
> +        _Adapter = NULL;
nullptr instead of NULL

2024-12-14 23:37 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    LuaAdapterBase* _Adapter = NULL; // Adapter for the version, see below
nullptr

2024-12-15 13:23 UTC, iMrShadow commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void _Shutdown();
I have seen in other projects that have dedicated cleanup functions. It depends on the usage.

In DirectXTex or Assimp, you don't call any news or deletes, they have their own dedicated functions for managing memory. Example:

```cpp
// Init the image
auto image = DirectXTex.CreateScrathImage();

image.doSomething();

// Free up the memory
image.Release();
```

2024-12-15 13:37 UTC, iMrShadow commented on TelltaleEditor/Source/ToolLibrary/Include/Core/Config.hpp
> +#define TTE_DEL(_Inst) delete _Inst
> The delete does not take in the type, perhaps it should? Not sure if there is a way to get the type through the variable. 

The delete should work fine, the type is determined during compile-time. 

```cpp
// One working example
Example* example = new Example();
delete example;
```

2024-12-15 13:38 UTC, LucasSaragosa commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void _Shutdown();
> What is the reason behind having a shutdown function? Why not have the code in the destructor directly?

good point. destructor can be used instead

2024-12-15 13:40 UTC, LucasSaragosa commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void* _State = NULL; // lua_State specific to the verison.
lua_State is defined differently for each lua version. i guess a predefine would work though, didnt even cross my head

2024-12-15 13:41 UTC, LucasSaragosa commented on TelltaleEditor/Source/ToolLibrary/Include/Core/Config.hpp
> +#define TTE_DEL(_Inst) delete _Inst
> The delete does not take in the type, perhaps it should? Not sure if there is a way to get the type through the variable. Maybe we could use templates
> 
> ```
> template <class T> inline T *alloc() { return new T(); }
> template <class T> inline void dealloc(T *ptr) { delete ptr; }
> ```
> 
> Or pass in the type in `#define TTE_DEL(_Type, _Inst) delete _Inst`

type isnt needed here. c++ delete keyword knows the type of what its deleting and will call its destructor followed by the memory free of operator delete(), so we dont really need this. the ppoint is the macro can be replaced in the future if needed

2024-12-15 13:42 UTC, iMrShadow commented on TelltaleEditor/Source/ToolLibrary/Include/Scripting/LuaManager.hpp
> +    void* _State = NULL; // lua_State specific to the verison.
Agreed.

2024-12-15 14:06 UTC, iMrShadow requested changes
Format code using our custom .clang-format.

2024-12-15 16:25 UTC, LucasSaragosa reviewed
looks good

2024-12-15 17:14 UTC, asilz commented on TelltaleEditor/Source/ToolLibrary/Include/Core/Config.hpp
> +#define TTE_DEL(_Inst) delete _Inst
A custom delete function in our library might require the type since it might want to call the destructor.

2024-12-16 22:42 UTC, iMrShadow commented on TelltaleEditor/Source/ToolLibrary/Source/Scripting/Adapter/Lua523.cpp
> +    luaL_dostring(<#L#>, <#s#>)
Missing semicolon.

2024-12-16 22:42 UTC, iMrShadow commented on TelltaleEditor/Source/ToolLibrary/Source/Scripting/LuaManager.cpp
> +    <#code#>;
'code' was not declared in this scope.

2024-12-17 16:09 UTC, LucasSaragosa commented on TelltaleEditor/Source/ToolLibrary/Source/Scripting/LuaManager.cpp
> +    <#code#>;
pushed without thinking woops

2024-12-17 18:48 UTC, merged